// <auto-generated />
using System;
using ArhiTodo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArhiTodo.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDataBase))]
    [Migration("20260226174848_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.BoardUserClaim", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Value")
                        .HasMaxLength(16)
                        .HasColumnType("boolean");

                    b.HasKey("Type", "BoardId", "UserId");

                    b.HasIndex("BoardId");

                    b.HasIndex("UserId");

                    b.ToTable("BoardUserClaims");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.InvitationLink", b =>
                {
                    b.Property<int>("InvitationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvitationLinkId"));

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationLinkName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<int>("Uses")
                        .HasColumnType("integer");

                    b.HasKey("InvitationLinkId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvitationKey")
                        .IsUnique();

                    b.ToTable("InvitationLinks");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.ProjectManager", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectManagers");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoinedViaInvitationKey")
                        .HasColumnType("text");

                    b.Property<int>("UserClaims")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.AssignedCardUser", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CardId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AssignedCardUsers");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BoardId"));

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("BoardId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CardListId")
                        .HasColumnType("integer");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CardUrgencyLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardId");

                    b.HasIndex("CardListId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.CardLabel", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer");

                    b.HasKey("CardId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("CardLabel");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.CardList", b =>
                {
                    b.Property<int>("CardListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardListId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<string>("CardListName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CardListId");

                    b.HasIndex("BoardId");

                    b.ToTable("CardLists");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Checklist", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChecklistId"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<string>("ChecklistName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChecklistId");

                    b.HasIndex("CardId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.ChecklistItem", b =>
                {
                    b.Property<int>("ChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChecklistItemId"));

                    b.Property<int>("ChecklistId")
                        .HasColumnType("integer");

                    b.Property<string>("ChecklistItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("IsDone");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabelId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<int>("LabelColor")
                        .HasColumnType("integer");

                    b.Property<string>("LabelText")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabelId");

                    b.HasIndex("BoardId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ProjectId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.BoardUserClaim", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Board", "Board")
                        .WithMany("BoardUserClaims")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.InvitationLink", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.ProjectManager", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Project", "Project")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.UserSession", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.AssignedCardUser", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Card", "Card")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Board", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Project", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Card", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.CardList", "CardList")
                        .WithMany("Cards")
                        .HasForeignKey("CardListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardList");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.CardLabel", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Card", "Card")
                        .WithMany("Labels")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.CardList", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Board", "Board")
                        .WithMany("CardLists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Checklist", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Card", "Card")
                        .WithMany("Checklists")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.ChecklistItem", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Checklist", null)
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Label", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Kanban.Board", "Board")
                        .WithMany("Labels")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Project", b =>
                {
                    b.HasOne("ArhiTodo.Domain.Entities.Auth.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Board", b =>
                {
                    b.Navigation("BoardUserClaims");

                    b.Navigation("CardLists");

                    b.Navigation("Labels");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Card", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("Checklists");

                    b.Navigation("Labels");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.CardList", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Checklist", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("ArhiTodo.Domain.Entities.Kanban.Project", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("ProjectManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
